"""Add SchemeMatch and Referral.document_id

Revision ID: e26c912cd2ab
Revises: 0001_initial_schema
Create Date: 2026-09-18 19:01:26.255130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e26c912cd2ab'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheme_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('scheme_id', sa.String(), nullable=False),
    sa.Column('clause_id', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'scheme_id', 'clause_id', name='uq_case_scheme_clause')
    )
    op.create_index(op.f('ix_scheme_matches_case_id'), 'scheme_matches', ['case_id'], unique=False)
    op.add_column('referrals', sa.Column('document_id', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('referrals', 'document_id')
    op.drop_index(op.f('ix_scheme_matches_case_id'), table_name='scheme_matches')
    op.drop_table('scheme_matches')
    # ### end Alembic commands ###
